### PR TITLE
Raty Copied

### PR DESCRIPTION
**Pull request by kifleW**

### CODE REVIEW

**Comment by amyxzhang** [comment]
Hey @kifleW, I don't think we need all these files. Can you please remove everything except what's inside raty/lib? Also I'd like each type of file in their respective places (css file in eyebrowse-chrome-ext/css, js file in eyebrowse-chrome-ext/libs, img files in eyebrowse-chrome-ext/img (ideally in their own folder called raty, font files in eyebrowse-chrome-ext/fonts. This may mean that you need to update relative file paths in the code.

**Comment by kifleW** [comment]
raty/lib? It's lib/raty right? Also, I believe all the changed files are from raty and I removed a .gitmodules file that I created previously. I could move each type of file in their respective places, but yeah that may mean updating relative file paths in the code. Is it worth it?

**Comment by amyxzhang** [comment]
I mean raty/lib here: https://github.com/wbotelhos/raty/tree/master/lib
See how all the files not inside /lib are useless to us (demo, spec, vendor, etc.)

Should just be a find and replace search query?

**Comment by amyxzhang** [comment]
If it's too hard, then just put raty/lib inside a folder called raty inside eyebrowse-chrome-ext/libs. Though I'd prefer to have the files split out like how it's currently done for the libraries we've imported, this way all images are served from /img etc.

**Comment by kifleW** [comment]
Lol. I get it now. Ok. I'll try doing this. I also wanted to look at a bug Soya mentioned before we merged anyhow.

**Pull request merged**
